# Get Azure Pipelines free plan
# Visit https://azure.microsoft.com/en-us/services/devops/pipelines/

trigger:
  - master

# Ensure this is the same as in build.gradle
#variables:
#  appPackaging: fxapp

jobs:
  # Linux job
  - template: ./build-job.yml
    parameters:
      name: Linux_JDK_8
      platform: linux
      jdkVersion: 1.8
      pool:
        vmImage: 'ubuntu-16.04'

  # Mac OS job
  - template: ./build-job.yml
    parameters:
      name: MacOS_JDK_8
      platform: mac
      jdkVersion: 1.8
      pool:
        vmImage: 'macOS-10.13'

  # Windows job
  - template: ./build-job.yml
    parameters:
      name: Windows_JDK_8
      platform: win
      jdkVersion: 1.8
      pool:
        vmImage: 'windows-2019'
